### ISSUE TITLE
Refactoring ideas

### ISSUE THREAD

**Issue by rikukissa** [joelbman/kzstats#1]
https://github.com/joelbman/kzstats/blob/master/src/js/services/player.js#L32-L39

Couldn't you just

```javascript
return $http.get('res/players.json');
```
instead?

------

https://github.com/joelbman/kzstats/blob/master/src/js/controllers/player/detail.js#L59-L61

```javascript
return fieldName === $scope.orderField;
```

------

https://github.com/joelbman/kzstats/blob/master/src/js/filters/index.js#L99-L103

Maybe functionality like this could also live outside of angular's context? For example you could have module called `utils.js`

```
module.exports = {
  numOnly: function(input) {
    return input.replace(/\D/g, '');
  }
}
```

And then you'd just do `app.filter('numOnly', function() { require('utils').numOnly.call(this, arguments); })` in your filters file and then for example [here](https://github.com/joelbman/kzstats/blob/master/src/js/controllers/player/detail.js#L75) you could just use `utils.numOnly(records[0].steamid)`. 

IMO it would feel a little cleaner and the functionality itself would be easier to test since you could just require it directly from the test file. On the other hand you would be bypassing angular's own DI, but you already got browserify there so what the heck.

Also [this](https://github.com/joelbman/kzstats/blob/master/src/js/controllers/player/list.js#L20) could use the same functionality.

**Comment by joelbman** [comment]
Thanks for the suggestions! I'll be implementing these soon.
