### ISSUE TITLE
New Website search does't work

### ISSUE THREAD

**Issue by lilgandhi1199** [joelbman/kzstats#3]
I see no way to only display 64 tick servers.
Of which one might be booting up shortly!
I'll never catch it if the filtering doesn't work

https://www.kzstats.com/servers
^^^ One of the buttons should offer tickrate that updates the page the second you click it.

https://www.kzstats.com/servers?mode=kz_timer&tick=64
^^^If it worked that would be fine but it doesn't and do I still have to click on "copy url" to actually filter by tickrate...
One click selecting the rate should update the page.

**Comment by joelbman** [comment]
I'll add this in the next update. I originally left it out because I didn't know if anyone actually uses the server page to look for 102/64 tick servers these days because their popularity has dropped significantly over the years.

**Comment by joelbman** [comment]
Added tíckrate filter in https://github.com/joelbman/kzstats/commit/ea11baac9aba8828ea490ff07ab97c8972e61ed8

**Comment by lilgandhi1199** [comment]
Awesome Thank You
